[package]
name = "gwaymaegyi"
description = "Native command-line interface for the gwaymaegyi chess engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gwaymaegyi-core.workspace = true
gwaymaegyi-search.workspace = true

[lints]
workspace = true
